server:
  # Configuration of Spring Boot embedded Tomcat server (java -jar petstore.jar)
  servlet:
    contextPath: ''
  port: "${PORT:8443}"
  http:
    port: 8080
endpoints:
  jmx:
    domain: petstore
logging:
  config: 'classpath:petstore-logback.xml'
spring:
  jmx:
    default-domain: petstore
  data:
    rest:
      defaultMediaType: application/json
      basePath: "/model"
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update # create | update | validate | create-drop
    properties:
      net.sf.ehcache.configurationResourceName: petstore-ehcache.xml
      hibernate:
        default_schema: public
        show_sql: false
        generate_statistics: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false
        cache:
          use_query_cache: true
          use_second_level_cache: true
          region.factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
  datasource:
    url: "${DB_URL:jdbc:postgresql://rdbms:5432/petstore}"
    username: "${DB_USERNAME:petstore}"
    password: "${DB_PASSWORD:petstore}"
    driver-class-name: org.postgresql.Driver
  flyway:
    # https://docs.spring.io/spring-boot/docs/current/reference/html/appendix-application-properties.html#data-migration-properties
    enabled: true
    sqlMigrationSuffix: .sql
    validate-on-migrate: false
    table: DB_MIGRATION_HISTORY
    baselineOnMigrate: true
    schemas: public
application:
  roles:
    admin:
      access-token: admin # Change in PRD with a UUID
